language: php

sudo: false

dist: trusty

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
cache:
  - composer
  - $HOME/.composer/cache

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: hhvm
      env: WP_VERSION=latest
    - php: nightly
      env: WP_VERSION=latest
  allow_failures:
    - php: nightly


before_script:
  - git clone https://github.com/Koodimonni/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer self-update
  - composer install

script:
  - composer test

notifications:
  email:
    on_success: never

branches:
  only:
    - master