language: php

sudo: false

dist: trusty

git:
  depth: 5

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    
cache:
  - composer
  - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: hhvm
      env: WP_VERSION=latest
    - php: nightly
      env: WP_VERSION=latest
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test travis '' 127.0.0.1 $WP_VERSION
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - composer test
